id: P010465
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG21844
  title: དྲང་ངེས་ལས་བརྩམས་པའི་བགྲོ་གླེང་སྐབས་ཀྱི་དྲིས་ལན་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    8a772e526d234550923bc3bc4da20895:
      image_group_id: I1KG22022
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
