id: I2B2B2A40
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T20:00:42+00:00'
last_modified: '2022-06-08T13:48:09.062773+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21844
  title: དྲང་ངེས་ལས་བརྩམས་པའི་བགྲོ་གླེང་སྐབས་ཀྱི་དྲིས་ལན་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F9C6:
      image_group_id: I1KG22022
      title: ''
      total_pages: 178
      order: 1
      base_file: F9C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
